### ISSUE TITLE
Problema ao executar itservices_zabbix.py

### ISSUE THREAD

**Issue by gilbertobr** [janssenlima/api-zabbix#1]
Estou utilizando seu código API Zabbix.
Mais tem dado um erro.
Teria como vc ajudar?
Segue abaixo o erro.

[root@SERVIDOR ~/api-zabbix]# python itservices_zabbix.py
  File "itservices_zabbix.py", line 26
    print x['name']
          ^
SyntaxError: Missing parentheses in call to 'print'

Estou utilizando o Python 3.5 é o Zabbix 3.0

**Comment by janssenlima** [comment]
Somente em Python 2.7.
Tem que portar o código para Python 3. Ainda não tive tempo para isso.
